### PR TITLE
Refactoring the AsyncLINQ implementation due to breaking changes in .NET 10 AsyncEnumerable

### PR DESCRIPTION
**Pull request by KrzysFR**
.NET 10 Preview 1 introduces an official `System.Linq.AsyncEnumerable` type that clashes with the existing type with the same name used by this library since ~10years now, causing overload resolution ambiguity errors that are difficult to quickly solve:

- All the async `Select(...)`, `Where(....)`, `ToListAsync(...)` methods in the new .NET 10 implementation either take or return `ValueTask<T>` instead of `Task<T>`. I'm sure there is a valid reason for this, but in the case of fdb queries, almost all async lambdas will return non-resolved tasks, and most of the methods in the binding return Task as well, making it very difficult to use.
- Renaming the old `AsyncEnumerable` to something else, would not help, because all the extensions methods that hook on `IAsyncEnumerable<T>` will have different type signatures (Task vs ValueTask), a no amount of `[OverloadResolutionPriority(...)]` will help (even if we bump the minimum version to .NET 9).
- The new `AsyncEnumerable` does not help fixing the issue of passing an `AsyncIterationHint` up the chain of LINQ operators, so that we can perform a range read in either `Iterator` or `WantAll` mode, depending on the operator used. This is very important for performance reasons in the case of the fdb binding. For example, `AnyAsync` or `FirstOrDefaultAsync` must only read one key from the cluster, and using streaming modes `Iterator` or `WantAll` would read too much, wasting bandwidth. Likewise, `ToListAsync` or `AllAsync` need to read all the keys, and the default streaming mode `Iterator` will only read a few keys on the first fetch, and require more round-trips to read everything, compared to using `WantAll`.
- The new `AsyncEnumerable` wants caller to pass a `CancellationToken` at the `ToListAsync(...)` call-site, even though we already have a token at the transaction level, forcing people to either live with false positive warnings from code analyzers, or have to pass `trans.Cancellation` again, which is redundant.
- This Async LINQ implementation is old and predates any official Async Linq NuGet library, or the ability to use `await foreach` and write async iterators with `yield return`.

Since there are now both great Async LINQ NuGet packages (for .NET 9 and lower) and the runtime team is adding in-box AsyncEnumerable for .NET 10+, the Async LINQ implementation in this repo does not need to be a generic purpose implementation anymore, and can focus specifically on async queries to a FoundationDB database (or similar use cases, where the source is a remote database, and the query runs inside a temporary transaction context).

This PR addresses most of this by the following:

- Add a new `IAsyncQuery<T>` which acts as a mirror of `IAsyncEnumerable<T>`. Since this is a different interface, it will not attempt to use the extensions methods defined in the new AsyncEnumerable type. The interface is compatible with the `await foreach` pattern, so most call sites that simply iterates other the results of a `GetRange` will not be impacted, apart from removing `ConfigureAwait(false)`.

- Add `IAsyncLinqQuery<T>`, which implements `IAsyncQuery<T>`, and adds most of the classical LINQ operators, like `Select`, `Where`, `AnyAsync`, `ToListAsync`, etc... This allows custom async iterators to add optimized implementations when they can do a better job than the generic fallback implementation. 

- Rename the old `AsyncEnumerable` to `AsyncQuery` and update all the previous extension methods to target `IAsyncQuery<T>`. All the methods will have the same shape as in .NET 10's `AsyncEnumerable`, except that all `ValueTask` are changed to `Task`.

- All extensions methods in `AsyncQuery` will test if the type implements `IAsyncLinqQuery<T>` and if yes, defer to the custom implementation. Otherwise, it will use a generic implementation for this operator.

- Change the `AsyncLinqIterator<T>` base class to expose all LINQ operators as `virtual` methods, that by default defer to the same fallback implementation as `AsyncQuery`. This means that any custom iterator can simply override any operator that it can optimize, without having to implement all of them every time.

- Add a few bridges between `IAsyncQuery<T>` and `IAsyncEnumerable<T>` with extension methods `ToAsyncQuery()` and `AsAsyncEnumerable()`.

- Go over all the existing overloads, and align with the new `AsyncEnumerable` API, meaning that the default lambda signatures are `Func<TResult, *>` and `Func<TResult, CancellationToken, Task<*>>`.

- Take the opportunity to change the namespace. Since the PR is a source breaking anyway, changing the namespace will ensure that all code that used the old interface names will break, instead of silently using different interfaces, or silently failing to build in net8.0 for multi-targeting projects (ex: you are writing code with `net10.0` selected, and will only notice an issue hours later when the CI build runs the `net8.0` variant).

### CODE REVIEW

**Comment by KrzysFR** [comment]
Here are some examples of the changes needed to fix application code after this PR:

### `ConfigureAwait(false)` in `await foreach`

__Before:__ `ConfigureAwait(false)` added due to recommendation by source code analyzers
```c#
await foreach(var kv in tr.GetRange(begin, end).ConfigureAwait(false))
// error CS1929: 'IAsyncQuery<int>' does not contain a definition for 'ConfigureAwait' and the best extension method overload 'TaskAsyncEnumerableExtensions.ConfigureAwait(IAsyncDisposable, bool)' requires a receiver of type 'System.IAsyncDisposable'
{
    // ...
}
```
__After:__ Simply remove ConfigureAwait(false) in the foreach clause
```c#
await foreach(var kv in tr.GetRange(begin, end))
{
    // ...
}
```

Note: the query implements the "await foreach pattern", which means that the compiler will generate the expected async state machine. Since async queries already encapsulate a CancellationToken (usually the token from the parent transaction), there is also no need to use `WithCancellation()`.

Please note that, `await foreach` will call the `GetAsyncEnumerator(CancellationToken)` overload on `IAsyncQuery` which will use `AsyncIterationMode.All` by default, instead of `Default`. This is done because this overload will be almost only called in this exact scenario where all results will be consumed.

### Interop to IAsyncEnumerable<T>

Application code needs to pass a query to a third-party method that wants an `IAsyncEnumerable<T>`, and where the argument type cannot be changed.

__Before:__ the result of GetRange() could be passed directly to the method
```c#
// application code
var query = tr.GetRange(....).Where(...).Select(...);
var results = await PostProcessResults(query); // error CS1503: Argument 1: cannot convert from `IAsyncQuery<...>` to `IAsyncEnumerable<...>`
// third party library
public static Task<T> PostProcessResults(IAsyncEnumerable<T> source) { ... }
```
__After:__ call `ToAsyncEnumerable()` to wrap the `IAsyncQuery<T>` into an `IAsyncEnumerable<T>`
```c#
// application code
var query = tr.GetRange(....).Where(...).Select(...);
var results = await PostProcessResults(query.ToAsyncEnumerable());
// third party library
public static Task<T> PostProcessResults(IAsyncEnumerable<T> source) { ... }
```

Note: the `ToAsyncEnumerable` method accepts a `AsyncIterationHint` argument that can be used to optimize for throughput or latency. If the methods that consumes the async enumerable is known to read *all* the results, you should pass `AsyncIterationHint.All`. If the method will only read a couple of elements, or will probably stop iterating before the end, pass either `AsyncIterationHint.Head` or `AsyncIterationHint.Iterator`.

```c#
// application code
var query = tr.GetRange(....).Where(...).Select(...);

// will use as few fetches as possible to read all results
var results = await PostProcessAllResults(query.ToAsyncEnumerable(AsyncIterationHint.All));
// will start with small pages and ramp up progressively
var results = await GetOnlyFirstPage(query.ToAsyncEnumerable(AsyncIterationHint.Iterator), 50);
// will start with very small page, and take more time to ramp up
var results = await GetNextMatchingResult(query.ToAsyncEnumerable(AsyncIterationHint.Head));
```

### Interop from IAsyncEnumerable<T> or IEnumerable<T>

If you are targeting .NET 10 exclusively, you should probably use the in-box AsyncEnumerable.

If you are multi-targeting, it is possible to wrap an existing `IAsyncEnumerable<T>` or `IEnumerable<T>` using the `ToAsyncQuery(...)` extension method.

Note that async queries need a root `CancellationToken`, which is required by `ToAsyncQuery`. You should pass the token that is tied to the lifetime of the query. If the query is started from inside a database transaction, in a HTTP request, or inside a Test method, the cancellation token for this context should be used. Please avoid using CancellationToken.None !

### Select vs SelectAsync

The new AsyncEnumerable adds async overloads for Select and Where that take async lambdas, with the same method name, while the Async LINQ implementation in this repo used different method names to workaround some overload resolution ambiguity between T and Task<T> which can now be solved with `OverloadResolutionPriorityAttribute`.

The new AsyncEnumerable all will execute the async handlers sequentially, while some of the existing SelectAsync methods could be configured to process items in parall (some sort of scatter/gather or fork-join).

These variants have been renamed to `SelectParallel` and accept a `ParallelAsyncQueryOptions` argument. All others have been renamed to simply `Select`

__Before:__ fan-out multiple sub-queries from the result of a previous range read
```c#
// open all the subdirectories
var folders = await children
	.ToAsyncQuery(tr.Cancellation)
	.SelectAsync((FdbPath child, CancellationToken _) => parent.OpenAsync(tr, FdbPath.Relative(child.Name)))
        // error CS1061: 'IAsyncLinqQuery<FdbPath>' does not contain a definition for 'SelectAsync' and no accessible extension method 'SelectAsync' accepting a first argument of type 'IAsyncLinqQuery<FdbPath>' could be found (are you missing a using directive or an assembly reference?)
	.ToListAsync()
	.ConfigureAwait(false);
```
__After:__ Simply replace `SelectAsync` by `SelectParallel`
```
// open all the subdirectories
var folders = await children
	.ToAsyncQuery(tr.Cancellation)
	.SelectParallel((FdbPath child, CancellationToken _) => parent.OpenAsync(tr, FdbPath.Relative(child.Name)))
	.ToListAsync()
	.ConfigureAwait(false);
```
